### ISSUE TITLE
Interface issue for assign() on intergers?

### ISSUE THREAD

**Issue by marehr** [edanor/umesimd#42]
Hi,

for `float` and `double` the interface is like this:

``` c++
assign(SIMDVecMask<4> const & mask, float b); // UMESimdVecFloat32_4
assign(SIMDVecMask<2> const & mask, double b); // UMESimdVecFloat64_2
```

Thus, the assignee type matches the scalar type of the vector.

For integers this isn't true:

```c++
assign(SIMDVecMask<4> const & mask, uint32_t b); // in avx512/uint/UMESimdVecUint16_4.h
assign(SIMDVecMask<4> const & mask, uint32_t b); // in avx512/uint/UMESimdVecUint32_4.h
assign(SIMDVecMask<8> const & mask, uint64_t b); // in avx512/uint/UMESimdVecUint64_8.h
```
----
I looked into the source code and apparently `avx512/uint/UMESimdVecUint16_4.h` was the only file where you didn't use  `uint16_t`. I thought this is a interface inconsistency, but it seems to be only a bug.

**Comment by edanor** [comment]
The files are present but not used at this moment. All 16b types will be reviewed and tested thoroughly before enabled. 

See: https://github.com/edanor/umesimd/blob/master/plugins/avx512/UMESimdVecUintAVX512.h#L50
