### ISSUE TITLE
Define a version macro in UMESimd.h header

### ISSUE THREAD

**Issue by amadio** [edanor/umesimd#58]
Hi Przemek,

Please consider defining something like a `UMESIMD_VERSION` macro in your main header (or a separate header). The only place where there is an indication of the version currently is in the README.md file,
and that may not be easily available for the CMake system of dependent libraries (e.g. VecCore) when
configuring software that requires specific versions.

**Comment by edanor** [comment]
I've added 3 macros (all defined at the top of UMESimd.h) : 
- UMESIMD_VERSION_MAJOR 
- UMESIMD_VERSION_MINOR 
- UMESIMD_VERSION_PATCH

**Comment by amadio** [comment]
Great! Thanks a lot!

**Comment by amadio** [comment]
Hi Przemek,

Looking at the version macros, I realized that they do not reflect the real version of the code.
The tag v0.6.1-stable is ~80 commits before the macros were created, and there is a tag v0.7.1 ~40 commits prior to the commit that closed this issue. Please make the macro version be the same as the git tag if possible. That is, if I do `git checkout vX.Y.Z` then the macros will contain numbers `X.Y.Z` as the version. Thanks!
