### ISSUE TITLE
Create an installation system for UME::SIMD

### ISSUE THREAD

**Issue by amadio** [edanor/umesimd#59]
Hi Przemek,

The current way of cloning the git repo and using the libraries straight from there will not work well for much longer, especially when UME::SIMD is used in other projects that will need to install it as a dependency.
I think this is the right time for you to think about how to resolve issue #47 and make a proper build system for your tests that also includes an installation procedure for the headers into /usr/include or some other path.

**Comment by edanor** [comment]
Hi Guillherme,

I've added basic installation file. Please propose specific modifications you think are necessary for your projects.

>>/.../ and make a proper build system for your tests /.../

What is it that you makes current test build system improper? It's simple, easy to use and it does the job and doesn't require much of additional maintenance.

The only improvement I could think of would be to be to have more automation. For example it would be nice to have possibility of testing all configurations with one-liner, but this is constrained by specific system settings (available compilers, OS, specific hardware). So in the end I don't think this would make testing task any more easier than it is now, and definitely not more transparent for new users.

**Comment by amadio** [comment]
Hi Przemek,

Thanks for the file. Please take a look at the [FHS](http://www.pathname.com/fhs) for good default places where to install stuff. It's not good to put everything inside `<PREFIX>/include/` like you are doing. Also, `include_directories()` is used to tell where to find headers, so it makes no sense in some places you are using, like `include_directories(doc)`, when `doc` only has a few text files. Maybe you meant `add_subdirectory()` instead. The [CMake reference documentation](https://cmake.org/cmake/help/latest) might be of help here. I will create a pull request with some changes soon for you to review. Best,
